name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"
      - "gha-migration"
  pull_request:
    branches:
      - "*"

# Declare default permissions as read only
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mqtt-bridge:
    name: Build MQTT Bridge
    timeout-minutes: 60
    strategy:
      matrix:
        # Java 21 is used as default version
        # In case of adding new version make sure that build-containers and deploy-java has correct static version set
        java:
          - version: "21"
            mainBuild: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/build-binaries
        with:
          javaVersion: ${{ matrix.java.version }}
          mainBuild: ${{ matrix.java.mainBuild }}
          runnerArch: "amd64"

  build-containers:
    name: Build Containers
    timeout-minutes: 60
    needs:
      - build-mqtt-bridge
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
          - s390x
          - ppc64le
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/build-containers
        with:
          architecture: ${{ matrix.architecture }}
          runnerArch: "amd64"

  push-containers:
    name: Push Containers
    timeout-minutes: 60
    needs:
      - build-mqtt-bridge
      - build-containers
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      DOCKER_REGISTRY: "quay.io"
      DOCKER_ORG: "strimzi"
      DOCKER_TAG: "latest"
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/push-containers
        with:
          architectures: "amd64,arm64,ppc64le,s390x"
          runnerArch: "amd64"
          quayUser: ${{ secrets.QUAY_USER }}
          quayPass: ${{ secrets.QUAY_PASS }}